# Generated by Django 5.1.1 on 2024-09-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fact",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
    ]
