# Generated by Django 5.1.1 on 2024-09-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0002_remove_fact_user_id_remove_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="user_id",
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(default="1", max_length=10),
            preserve_default=False,
        ),
    ]
