# Generated by Django 5.1.1 on 2024-09-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0003_fact_user_id_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="fact_id",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
    ]
