# Generated by Django 5.1.1 on 2024-09-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0004_fact_fact_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
